#!/usr/bin/env ansible-playbook
# vim: noai:ts=2:sw=2:et
---

- name: "Test k5_network module"

  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - k5_auth:
        username: "crossn"
        region_name: "uk-1"
      register: k5_auth_reg

    #- debug: var=k5_auth_reg
    - debug: var=k5_auth_reg.k5_auth_facts.auth_token

    - k5_floating_ip:
        server: "nx-demo01-1a-jumpserver"
        fixed_ip: "10.70.1.253"
        ext_network: "inf_az1_ext-net02"
        k5_auth: "{{ k5_auth_reg.k5_auth_facts }}"
      register: k5_fip_reg

    - debug: var=k5_fip_reg


